<?php

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        Product::insert([
            [
                'category_id' => 1,
                'name' => 'Марио',
                'description' => 'Куриная грудка, охотничьи колбаски, Дор Блю,сладкий перец, шпинат, томатный и сливочный соус.',
                'image' => 'products/YeFhjCFAe2L4UA0UDKwPv4z8lJ7oU01qdjqzAn2J.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'Мясное ассорти',
                'description' => 'Томатный соус, карбонат в/к, бекон, салями, куриная грудка, томат, сладкий перец, сладкий лук, зелень.',
                'image' => 'products/wBuuSGgPJzfYFlPTpmTKC2MrTpKrMO9ewdvVpi5y.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'Охотничья ассорти',
                'description' => 'Охотничьи колбаски, маринованные огурчики, обжаренные с луком грибы, томатный соус, зелень.',
                'image' => 'products/vgGDKPSmkp5k5RSmtbomUoOQellKIAKnljbmySO8.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'Пепперони',
                'description' => 'Пикантные колбаски Пепперони с моцареллой Гальбани на томатном соусе.',
                'image' => 'products/n19cKsuoJWR0U1sc4VRBgqZN5plFzXzLynFRuaaB.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С белыми грибами',
                'description' => 'Грибы шампиньоны и белые обжаренные с луком на сливочном соусе с Рукколой и моцареллой Гальбани.',
                'image' => 'products/0wAz37CeCTajWZs9hkiX58de8ulsd9VbEIQqH61Q.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С ветчиной',
                'description' => 'Карбонат в/к, бекон, сладкий перец, маслины, красный лук, томатный соус, зелень.',
                'image' => 'products/gDo2zeTleMq1wvHg5hUDQpxoMfzrJOJ7X5jXcXVm.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С креветками и рукколой',
                'description' => 'На томатном соусе со свежей рукколой, моцареллой Гальбани и соусом Песто.',
                'image' => 'products/pqUSIvSvwPjvnrCPcDWrK2GWhNXmkx0XAjFp8D1B.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С лососем',
                'description' => 'Сливочный соус, филе семги, маслины, лимон, базиликовое масло.',
                'image' => 'products/j5cjsE8TMs6R83DESzcKC0S28vVqZKng1J9hPL84.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С цыпленком барбекью',
                'description' => 'Куриная грудка, томат, сладкий перец, томатный соус, зелень, соус Барбекью.',
                'image' => 'products/KJxqueEDooH0axWKSqHYtxdGwBgIIIS4ZAuZTLXt.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С цыпленком и грибами',
                'description' => 'Куриная грудка, бекон, обжаренные с луком шампиньоны, красный лук, сливочный соус, зелень.',
                'image' => 'products/77muu4yto6m60lyRgrDfxYInulQNvswkrpAi24Zj.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'С цыпленком и рукколой',
                'description' => 'На сливочном соусе с томатами Черри и сыром Грано Падано',
                'image' => 'products/xuT3YTmR5cAoTUUOun7X0s3jYLBS1k643iBJb4aW.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'name' => 'Стафф пицца',
                'description' => 'Закрытая пицца с запеченной шейкой, карбонатом, куриным филе, сладким перцем, грибами и томатами. ',
                'image' => 'products/96bUMQJLLUNBWKcakmoxP5B6PPOxiFeSSM4AFa41.jpeg',
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Калифорния Маки',
                'description' => 'Мясо краба, огурец, авокадо, икра Тобико.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Канада Маки',
                'description' => 'Угорь, лосось, крем сыр, авокадо, огурец.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Манго Маки',
                'description' => 'Лосось, манго, крем сыр, огурец, икра Тобико.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Мидори Маки',
                'description' => 'Лосось, крем сыр, огурец, лук зелёный, икра Тобико, кунжут.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Моши Маки',
                'description' => 'Крем-краб, лосось, огурец, икра Тобико.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Норвегия Маки',
                'description' => 'Лосось, сливочный сыр, омлет, огурец, кунжут.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Нормальная Филадельфия',
                'description' => 'Правильное сочетание риса, рыбы и сыра. Сделана по рецептуре 2005 года: 100 гр рис, 100 гр лосося, 50 гр сыра.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Огненный',
                'description' => 'Креветка, лосось, огурец, лук зеленый, крем сыр, спайси соус, кунжут.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Очень вкусный ролл',
                'description' => 'Угорь, лосось, икра лосося, крем сыр, зелёный лук.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ролл Зебра',
                'description' => 'Угорь, креветка, крем сыр, огурец, кунжут.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'name' => 'Ролл Королевский Дракон',
                'description' => 'Очень много угря, крем сыр, омлет Тамаго, огурец.',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'name' => 'Мини сет №7 ',
                'description' => 'Манго маки, Мидори маки, Эби чиз маки',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'name' => 'Мини сет №8 ',
                'description' => 'Огненный ролл, Сакура маки, Теплый с креветкой и манго',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'name' => 'Мини сет №9 ',
                'description' => 'Сакура маки, Сливочный лосось, Эби чиз маки',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'name' => 'Мини сет №10 ',
                'description' => 'Манго маки, Сакура маки, Филадельфия в кунжуте',
                'image' => null,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
        ]);
    }
}
