<?php

use App\Models\SizeProduct;
use Illuminate\Database\Seeder;

class SizeProductSeeder extends Seeder
{
    public function run()
    {
        SizeProduct::insert([
            [
                'category_id' => 1,
                'product_id' => 1,
                'size' => '23 см',
                'price' => 195,
                'weight' => 350,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 1,
                'size' => '32 см',
                'price' => 390,
                'weight' => 670,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 2,
                'size' => '23 см',
                'price' => 240,
                'weight' => 360,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 2,
                'size' => '32 см',
                'price' => 490,
                'weight' => 750,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 3,
                'size' => '23 см',
                'price' => 185,
                'weight' => 320,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 3,
                'size' => '32 см',
                'price' => 370,
                'weight' => 660,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 4,
                'size' => '23 см',
                'price' => 190,
                'weight' => 290,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 4,
                'size' => '32 см',
                'price' => 450,
                'weight' => 650,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 5,
                'size' => '23 см',
                'price' => 210,
                'weight' => 310,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 5,
                'size' => '32 см',
                'price' => 470,
                'weight' => 700,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 6,
                'size' => '23 см',
                'price' => 180,
                'weight' => 300,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 6,
                'size' => '32 см',
                'price' => 360,
                'weight' => 610,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 7,
                'size' => '23 см',
                'price' => 250,
                'weight' => 300,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 7,
                'size' => '32 см',
                'price' => 490,
                'weight' => 630,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 8,
                'size' => '23 см',
                'price' => 210,
                'weight' => 310,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 8,
                'size' => '32 см',
                'price' => 410,
                'weight' => 640,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 9,
                'size' => '23 см',
                'price' => 190,
                'weight' => 350,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 9,
                'size' => '32 см',
                'price' => 390,
                'weight' => 700,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 10,
                'size' => '23 см',
                'price' => 190,
                'weight' => 340,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 10,
                'size' => '32 см',
                'price' => 390,
                'weight' => 700,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 11,
                'size' => '23 см',
                'price' => 190,
                'weight' => 290,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 11,
                'size' => '32 см',
                'price' => 390,
                'weight' => 550,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 12,
                'size' => '23 см',
                'price' => 240,
                'weight' => 450,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 1,
                'product_id' => 12,
                'size' => '32 см',
                'price' => 495,
                'weight' => 900,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 13,
                'size' => '6 шт',
                'price' => 430,
                'weight' => 210,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 14,
                'size' => '6 шт',
                'price' => 390,
                'weight' => 240,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 15,
                'size' => '6 шт',
                'price' => 270,
                'weight' => 220,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 16,
                'size' => '6 шт',
                'price' => 265,
                'weight' => 210,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 17,
                'size' => '6 шт',
                'price' => 260,
                'weight' => 230,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 18,
                'size' => '6 шт',
                'price' => 210,
                'weight' => 210,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 19,
                'size' => '6 шт',
                'price' => 375,
                'weight' => 250,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 20,
                'size' => '6 шт',
                'price' => 240,
                'weight' => 210,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 21,
                'size' => '6 шт',
                'price' => 375,
                'weight' => 230,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 22,
                'size' => '6 шт',
                'price' => 285,
                'weight' => 220,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 4,
                'product_id' => 23,
                'size' => '5 шт',
                'price' => 475,
                'weight' => 270,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'product_id' => 24,
                'size' => '3 шт',
                'price' => 360,
                'weight' => 300,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'product_id' => 25,
                'size' => '3 шт',
                'price' => 340,
                'weight' => 310,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'product_id' => 26,
                'size' => '3 шт',
                'price' => 350,
                'weight' => 300,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
            [
                'category_id' => 3,
                'product_id' => 27,
                'size' => '3 шт',
                'price' => 370,
                'weight' => 300,
                'created_at' => date_create(),
                'updated_at' => date_create(),
            ],
        ]);
    }
}
